# Python assignment-1

Name : S.Janane                              

Reg.no : 21UAI040    
    
Dept.name : AI&DS   
    
Section : A

In [12]:
# Write a function called show_stars(rows). If rows are 5, it should print the following:

num=5
print("Star Pattern: ")
for i in range(0,num):
    for j in range(0,i+1):
        print("*", end=' ')
    print("\r")

Star Pattern: 
* 
* * 
* * * 
* * * * 
* * * * * 


In [2]:
# Print the following pattern

rows = 6
for i in range(rows):
    for j in range(i):
        print(i, end=' ')
    print('')


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [3]:
#Write a program to remove characters from a string starting from zero up to n and return a new string.

instr =input("enter the string:")
print ("Original string: " + instr) 
   
rstr = "" 
   
for i in range(0, len(instr)): 
    if i != 3: 
        rstr = rstr + instr[i] 
print ("String after removal of i'th character : " + rstr)

enter the string:hi!hello
Original string: hi!hello
String after removal of i'th character : hi!ello


In [7]:
#Iterate the given list of numbers and print only those numbers which are divisible by 5
nums = [] 
for i in range(5): 
    num = int(input('Give me a number:')) 
    nums.append(num) 
 
for i in nums: 
    if i % 5 == 0: 
        print(i) 

Give me a number:5
Give me a number:10
Give me a number:45
Give me a number:7
Give me a number:9
5
10
45


In [9]:
# Write a program to find how many times substring “Hi” appears in the given string.

string = "hi hello hi gm"
substring = "hi"
count = string.count(substring)
print("The count is:", count)

The count is: 2


In [10]:
# Python program to interchange first and last elements in a list

def swapList(list):
    first = list.pop(0)   
    last = list.pop(-1) 
    list.insert(0, last)  
    list.append(first)         
    return list
li = [1, 9, 2, 10, 19, 30]
print(li)
print("Swapped list: ",swapList(li))

[1, 9, 2, 10, 19, 30]
Swapped list:  [30, 9, 2, 10, 19, 1]


In [11]:
# Python program to swap two elements in a list

def swapPositions(list, pos1, pos2):
    get = list[pos1], list[pos2]
    list[pos2], list[pos1] = get
    return list
List = [13,87,2,90]
pos1, pos2  = 1, 3
print(swapPositions(List, pos1-1, pos2-1))

[2, 87, 13, 90]


In [12]:
# Python | Ways to find length of list

test= [1,2,4,6,13,9,7,12]
print ("The list is : " + str(test))
count = 0
for i in test:
    count = count + 1
print ("Length of list using naive method is : " + str(count))

The list is : [1, 2, 4, 6, 13, 9, 7, 12]
Length of list using naive method is : 8


In [13]:
# Maximum of two numbers in Python

n1 = int(input("Enter the number 1: "))
n2 = int(input("Enter the number 2: "))
if(n1 > n2):
  print(n1, "is greater")
elif(n1 < n2):
    print(n2, "is greater")
else:
    print("Both are equal")

Enter the number 1: 27
Enter the number 2: 18
27 is greater


In [14]:
# Minimum of two numbers in Python

def minimum(a, b):      
    if a <= b:
        return a
    else:
        return b
a = int(input("Enter the number a:"))
b = int(input("Enter the number b:"))
print(minimum(a, b))

Enter the number a:9
Enter the number b:4
4


In [15]:
# Python program to check whether the string is Symmetrical or Palindrome

def check(string):
    n=len(string)
    flag=0
    if n%2:
        mid=n//2+1
    else:
        mid= n//2
    start=0
    end= mid
    while(start <mid and end<n):
        if(string[start]== string[end]):
            start= start+1
            end= end+1
        else:
            flag=1
            break
    if flag==0:
        print("symmetrical")
    else:
        print("not symmetrical")
s= "abcabc"
print (s)
check(s)
s2= "abcdab"
print(s2)
check(s2)

abcabc
symmetrical
abcdab
not symmetrical


In [17]:
# Reverse words in a given String in Python

def function(x):
  return x[::-1]
txt = function("python")
print(txt)

enanaj


In [18]:
# Ways to remove i’th character from string in Python

def remove_char(s, i):
    for j in range(len(s)):
        if j==i:
            s=s.replace(s[i],"",1)
    return s
string = "Welcome to Python"
i = 5
print(remove_char(string,i-1))

Welcme to Python


In [20]:
# Python – Maximum and Minimum K elements in Tuple

my_tuple = (7, 25, 36, 9, 6, 8)
print("The tuple is : ")
print(my_tuple)
K = 2
print("The value of K has been initialized to ")
print(K)
my_result = []
my_tuple = list(my_tuple)
temp = sorted(my_tuple)
for idx, val in enumerate(temp):
   if idx < K or idx >= len(temp) - K:
      my_result.append(val)
my_result = tuple(my_result)

print("The result is : " )
print(my_result)

The tuple is : 
(7, 25, 36, 9, 6, 8)
The value of K has been initialized to 
2
The result is : 
(6, 7, 25, 36)


In [22]:
# Python | Sort Python Dictionaries by Key or Value

dict1 = {1: 1, 2: 9, 3: 4}
sortvalues = sorted(dict1.values()) 
sortdict = {}

for i in sortvalues:
    for k in dict1.keys():
        if dict1[k] == i:
            sortdict[k] = dict1[k]
            break
print(sortdict)

{1: 1, 3: 4, 2: 9}


In [24]:
# Find the size of a Set in Python

set = {'a', 'b', 'c','d','e','g','h'}
length = len(set)
print(f'Length of this set is {length}')

Length of this set is 7


In [27]:
# Iterate over a set in Python

thisset = {"python", "c", "java"}
for x in thisset:
  print(x)

c
python
java


In [28]:
# How to get list of parameters name from a function in Python?

import inspect
import collections
print(inspect.signature(collections.Counter))

(iterable=None, /, **kwds)


In [5]:
# Python program to Find the size of a Tuple

a = ("python","c","c++","javascript","html")
b = (2,5,8,2,6,8,4) 
print("Size of the tuple is", len(a))
print("Size of the tuple is", len(b))

Size of the tuple is 5
Size of the tuple is 7


In [4]:
# Python – Sum of tuple elements

Tuple = (3,87,445,72,89,200)
print("Tuple Items = ", Tuple)

tupleSum = sum(Tuple)
print("\nThe Sum of numTuple Tuple Items = ", tupleSum)

Tuple Items =  (3, 87, 445, 72, 89, 200)

The Sum of numTuple Tuple Items =  896


In [10]:
# Adding and Subtracting Matrices in Python

import numpy as np
a= np.array([[1, 2], [3, 4]])
b= np.array([[5, 6], [7, 8]])
print("Printing elements of matrix 1:")
print(a)
print("Printing elements of matrix 2:")
print(b)
print("Addition of two matrix")
print(np.add(a,b))
print("Subtraction of two matrix")
print(np.subtract(a,b))

Printing elements of matrix 1:
[[1 2]
 [3 4]]
Printing elements of matrix 2:
[[5 6]
 [7 8]]
Addition of two matrix
[[ 6  8]
 [10 12]]
Subtraction of two matrix
[[-4 -4]
 [-4 -4]]
