# PYTHON ASSIGNMENT

NAME: S.JANANE

DEPT.: AI&DS-"A"
    
I YEAR IISEM

REG.NO: 21UAI040

In [4]:
class Parent:
    def func1(self):
        print("This is a parent class.") 
class Child(Parent):
    def func2(self):
        print("This is a child class.")
obj=Child()
obj.func1()
obj.func2()

This is a parent class.
This is a child class.


In [6]:
class Mother:
    mname = "" 
    def mother(self):
        print(self.mname)
class Father:
    fname = "" 
    def father(self):
        print(self.fname) 
class daughter(Mother, Father):
    def parents(self):
        print("Father Name is:", self.fname)
        print("Mother Name is:", self.mname)
s1 = daughter()
s1.fname = "Sundar"
s1.mname = "Priya"
s1.parents()

Father Name is: Sundar
Mother Name is: Priya


In [11]:
class sum:  
    def add(self,a,b):  
        return a+b;  
class multipli:  
    def product(self,a,b):  
        return a*b;  
class division(sum,multipli):  
    def divide(self,a,b):  
        return a/b;  
d = division()  
print(d.add(100,620))  
print(d.product(107,290))  
print(d.divide(70,6))  

720
31030
11.666666666666666


In [15]:
class Grandfather: 
    def __init__(self, gname):
        self.gname = gname
class Father(Grandfather):
    def __init__(self, fname, gname):
        self.fname = fname
        Grandfather.__init__(self, gname)
class daughter(Father):
    def __init__(self, dname, fname, gname):
        self.dname = dname
        Father.__init__(self, fname, gname) 
    def print_name(self):
        print('Grandfather name :', self.gname)
        print("Father name :", self.fname)
        print("Daughter name :", self.dname)
s1 = daughter('xay', 'abc', 'xyz')
s1.print_name()

Grandfather name : xyz
Father name : abc
Daughter name : xay


In [16]:
import re
t="This the python program for regex"
x = re.findall("e",t)
print(x)

['e', 'e', 'e']


In [17]:
import re
t="This the python program for regex"
x = re.search("t", t)
print("The first t character is found at the position:", x.start())

The first t character is found at the position: 5


In [18]:
import re
t="This the python program for regex"
x=re.split("p", t)
print(x)

['This the ', 'ython ', 'rogram for regex']


In [23]:
import re
t="This the python program for regex"
x=re.sub("o", "0", t)
print(x)

This the pyth0n pr0gram f0r regex


In [24]:
import numpy as np 
a = np.array([[12,54,12,57,8,4,12]])
print("Mean:", np.mean(a)) 
print("Std:", np.std(a)) 
print("Var:", np.var(a)) 
print("Sum:", np.sum(a)) 
print("Prod:", np.prod(a))
print("min:",np.min(a))
print("max:",np.max(a))
print("cumulative sum:",np.cumsum(a))
print("cumulative product:",np.cumprod(a))
print("argument min:",np.argmin(a))
print("argument max:",np.argmax(a))

Mean: 22.714285714285715
Std: 20.926499166055912
Var: 437.9183673469388
Sum: 159
Prod: 170201088
min: 4
max: 57
cumulative sum: [ 12  66  78 135 143 147 159]
cumulative product: [       12       648      7776    443232   3545856  14183424 170201088]
argument min: 5
argument max: 3


In [6]:
def fun(a):
    if a < 7:
        b = a/(a-3)
    print("Value of b = ", b) 
try:
    fun(0)
    fun(3)
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")

Value of b =  -0.0
ZeroDivisionError Occurred and Handled


In [8]:
a = [1,62,43]
try: 
    print ("Second element = %d" %(a[4]))
    print ("Fourth element = %d" %(a[2]))
  
except:
    print ("An error occurred")

An error occurred


In [11]:
while True:
...     try:
...         x = int(input("Please enter a number: "))
...         break
...     except ValueError:
...         print("Oops!  That was no valid number.  Try again...")
...

Please enter a number: 445


In [12]:
try:
  f = open("pyfile.txt")
  try:
    f.write("python program")
  except:
    print("Something went wrong when writing to the file")
  finally:
    f.close()
except:
  print("Something went wrong when opening the file")

Something went wrong when opening the file


In [20]:
a = 356
try:
     b = 35
     p = a*b
except:
    print("indentation error is occured")
print(p)

12460


In [23]:
try:
  print(f)
except NameError:
  print("Variable s is not defined")
except:
  print("Something else went wrong")

Variable s is not defined


In [25]:
import numpy as np
x = np.random.randint(1, 100, size = (4,3))
print(x)
print()

[[34 57 27]
 [ 1 78 78]
 [66 86 90]
 [89 87 66]]

